version: '3'

services:
  web:
    build: .
    command: gunicorn finance_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/code
      - static_volume:/code/staticfiles  # Ensure static files are preserved
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    environment:
      - DEBUG=0  # Set DEBUG to False in production

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=finance_db
      - POSTGRES_USER=finance_user
      - POSTGRES_PASSWORD=786Postgre

volumes:
  postgres_data:
  static_volume:  # Static volume to persist static files
