# Generated by Django 3.2.25 on 2024-10-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('symbol', 'date')},
            },
        ),
    ]
