# Generated by Django 3.2.25 on 2024-10-20 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0002_auto_20241017_1553'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='adjusted_close_price',
        ),
        migrations.RemoveField(
            model_name='stockdata',
            name='dividend_amount',
        ),
    ]
