name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t your_dockerhub_username/your_app_name:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push your_dockerhub_username/your_app_name:${{ github.sha }}

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull your_dockerhub_username/your_app_name:${{ github.sha }}
            docker stop your_app_container || true
            docker rm your_app_container || true
            docker run -d --name your_app_container -p 80:8000 --env-file /home/ubuntu/.env your_dockerhub_username/your_app_name:${{ github.sha }}
