name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.21.6
          pip install Cython
          pip install pmdarima
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: finance_project.settings_ci
        run: |
          python manage.py test

      # Step 5: Deploy to EC2
      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          # Save the private key to a file
          echo "${PRIVATE_KEY}" > private_key
          chmod 600 private_key
          
          # Transfer code to EC2 using rsync
          rsync -avz -e "ssh -i private_key -o StrictHostKeyChecking=no" \
            --exclude 'venv/' \
            --exclude '.git/' \
            ./ QuantumBull/ $USERNAME@$HOSTNAME:/home/ubuntu/quantummaze/QuantumBull/
          
          # SSH into EC2 and perform deployment steps
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME << 'EOF'
            echo "Connected to EC2, performing cleanup..."

            # Stop and remove existing Docker containers
            docker stop quantumleap || true
            docker rm quantumleap || true

            echo "Removing unused Docker images and freeing up space..."
            docker system prune -a --volumes -f

            echo "Navigating to project directory..."
            cd /home/ubuntu/quantummaze/QuantumBull/

            echo "Building Docker image without cache..."
            docker build --no-cache -t hannanshah/quantummaze:latest .

            echo "Running new Docker container..."
            docker run -d --name quantumleap -p 80:8000 --env-file /home/ubuntu/.env --restart unless-stopped hannanshah/quantummaze:latest

            echo "Deployment completed successfully!"
          EOF
          
          # Clean up the private key file
          rm private_key
