name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: finance_project.settings_ci
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t hannanshah/quantumbull:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push hannanshah/quantumbull:${{ github.sha }}

      - name: Setup SSH
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: SSH to EC2 and deploy
        run: |
          ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            docker pull hannanshah/quantumbull:${{ github.sha }}
            docker stop crazy_antonelli || true
            docker rm crazy_antonelli || true
            docker run -d --name crazy_antonelli -p 80:8000 --env-file /home/ubuntu/.env hannanshah/quantumbull:${{ github.sha }}
          EOF
