name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy==1.21.6
          pip install Cython
          pip install pmdarima
          pip install -r requirements.txt

      # Step 4: Run Tests
      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: finance_project.settings_ci
        run: |
          python manage.py test

      # Step 5: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t hannanshah/quantumbull:${{ github.sha }} .

      # Step 6: Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 7: Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push hannanshah/quantumbull:${{ github.sha }}

      # Step 8: Deploy to EC2 via SSH using the Lets.pem file
      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ${{ secrets.EC2_USERNAME }}
        run: |
          echo "Connecting to EC2 instance using Lets.pem and pulling Docker image..."
          chmod 600 ./Lets.pem
          ssh -o StrictHostKeyChecking=no -i ./Lets.pem $USERNAME@$HOSTNAME << 'EOF'
            echo "Connected to EC2, executing Docker commands..."
            docker pull hannanshah/quantumbull:${GITHUB_SHA}
            echo "Stopping existing container if it exists..."
            docker stop crazy_antonelli || true
            echo "Removing old container if it exists..."
            docker rm crazy_antonelli || true
            echo "Running new Docker container..."
            docker run -d --name crazy_antonelli -p 80:8000 --env-file /home/ubuntu/.env --restart unless-stopped hannanshah/quantumbull:${GITHUB_SHA}
            echo "Deployment completed!"
          EOF
