name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Build Docker image for testing
      - name: Build Docker image for testing
        run: |
          docker build --no-cache -t hannanshah/quantummaze:latest .

      # Run tests inside Docker container
      - name: Run Tests inside Docker container
        run: |
          docker run hannanshah/quantummaze:latest python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Deploy to EC2 and build Docker image locally with no cache
      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME << 'EOF'
            echo "Connected to EC2, pulling and running Docker image..."
            docker pull hannanshah/quantummaze:latest
            echo "Stopping existing container if it exists..."
            docker stop quantumleap || true
            echo "Removing old container if it exists..."
            docker rm quantumleap || true
            echo "Running new Docker container..."
            docker run -d --name quantumleap -p 80:8000 --env-file /home/ubuntu/.env --restart unless-stopped hannanshah/quantummaze:latest
            echo "Deployment completed!"
          EOF
