name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DJANGO_SETTINGS_MODULE: finance_project.settings_ci
        run: |
          python manage.py test

      - name: Build Docker image
        run: |
          docker build -t hannanshah/quantumbull:${{ github.sha }} .

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push hannanshah/quantumbull:${{ github.sha }}

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: MIIEpQIBAAKCAQEA4NvoHUVXRITKWc3o5HLPQKO741FeVJe0jXTyhw1J0RaRmZnL
DsEnhbBAxCRaOi+Yi8eLG9NVchHfgYjZZ1uV9WHbhi27n8p/CXLSkRKg3xihxOoN
rDwNwGTHVF2eJyQiDb7pTvcZWM3oIveat3nD7XJYZcvART7Kjbeq4aPH6dSgbt7R
cktzrFo3lUqqweQ5AflV0Q84fg2cMXUxUFDnn9Fj6HimDOfJzmQK7a5b0JiyQTeU
jHEd0ueH56IPE27nyqrRazCuiaJLKVtgMRv2WxzL9URleqncSy2qRmbeM/ui/YGc
E5iVNvQhYxiF5VTIG6v2+bL8XxxYHPbSHsTZVwIDAQABAoIBAQC/gYsGou/YI2BT
a9NV/ZIV810qFTrJwQq9D0UfUGn18cq/jwQp5MfMTHhclLljpPW+1ovbfvne1OoO
YIcISDBHdLiKZpjNVqErYueDNuJcH5ZnJw/OCLeNjEdXywPPQi7eliIOZtTnlTaH
0WmrqcD8kc5HpGh0kS3h1PNsiRjSQ/PBl2lPj+9Z/nLNSwXWggPdyr6+UlJfvKgD
1jGtPHxljoLaI99IeqlT4oi5/9YfIfpuAFcsf07IJdXE1EaZRaSF7FHhhVv2U1w0
cr7bW3pr/52zuK50HV0cOd4qgRzm7OzkN7GziE96FGlI0uFaNQtTFrdz35ciPaLW
aOCuUQmBAoGBAPzVI6yajgp/Qerg1meBcOSoNsO6o6PC1A8Wd3Q9wmt2Aa0yQj7o
QbzaZ1Wkdg2m23/Etqqg00mfh/Vgt7VnmSigSugUTzaoxEZPtd3TbHLqlQVBQ453
ikZ9q1ZbOG5G3glTcbTppefur27D622++pCem7jWfPXRG1Xl/zi/GSO/AoGBAOOt
DZ073dn+w1XvInY/IVlEqyPu701RvWL7E81GTPt5o8qh7X1JAGDDpWWR+kI0yGr0
lXAB5UDPu8CQMGqPkArFd8MdwTpBcZUfu6fyf2I8WFNdaugNTmYFwzmXKPkLRJ9+
OxlX/Ld4weAYiL2uRFKtOwz1WbaOyg61R9lCFtBpAoGARGdZ/oHWOirR570q5NgV
dhe4sV3WliDJBMf8S5vF9RL5QyWc3K4z0ud4G6iiM/FX44qSLTnT0FB0FUQ0j8TW
oDI18fJEuDIS4D8ComBoL/MdnE1a/LmE1Kt9ZqDJdLSBsB4+Xkb0lvpxxlMFaCzK
V8RBt1F4f30ymxvd4Dl7kLsCgYEAj8PLr/iIm0nSwKWzBiXRAhRpWNRciV9PDnxq
wZldrQHfWmmrlAwP0Apam2t1Mm8wCtGMt2CLCcTi0rJ50B/9HcAZYrycMhP3C+ow
zdlDdJ2UTHfVtNgKJEQJRYlc1v21hFzqJpO3wYbgLYhweA3dmLNIcWNQFgXOM0Fn
MBoaW9kCgYEAsQP/++Zy41o/krc1+t8bV9qyPXMQlmRw+0BZqXai0xkhzNqRHiiC
apdmRwvvTYCFhgRQ0CaiWEIOClR85Ajrw1Fq1+iA+Yo+2zch92+0pb5Pqs0TUBfy
WVm8OxQSdus5gd9DyASWM6CMaLunZP5dBpumkGHruBwzUWN15+XilHU=
          HOSTNAME: 18.118.34.61 
          USERNAME: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME << 'EOF'
            docker pull hannanshah/quantumbull:${{ github.sha }}
            docker stop crazy_antonelli || true
            docker rm crazy_antonelli || true
            docker run -d --name crazy_antonelli -p 80:8000 --env-file /home/ubuntu/.env hannanshah/quantumbull:${{ github.sha }}
          EOF
