name: CI/CD Pipeline

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          sudo docker build -t hannanshah/quantummaze:latest .

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          sudo docker push hannanshah/quantummaze:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          HOSTNAME: ${{ secrets.EC2_HOST }}
          USERNAME: ubuntu
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$HOSTNAME << 'EOF'
            echo "Connected to EC2, pulling and running Docker image..."
            sudo docker pull hannanshah/quantummaze:latest
            echo "Stopping existing container if it exists..."
            sudo docker stop quantumleap || true
            echo "Removing old container if it exists..."
            sudo docker rm quantumleap || true
            echo "Running new Docker container..."
            sudo docker run -d --name quantumleap -p 80:8000 --env-file /home/ubuntu/.env --restart unless-stopped hannanshah/quantummaze:latest
            sudo docker ps
            echo "Deployment completed!"
          EOF
